name: Build, Publish, Deploy

on: 
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          curl -o /tmp/filerun.zip -L 'https://filerun.com/download-latest-docker'
          echo "FILERUN_INSTALL_VERSION=`unzip -p /tmp/filerun.zip initial_version.txt`" >> $GITHUB_ENV
          rm -f /tmp/filerun.zip

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set env
        run: |
          export IMAGE=ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:test-${{ env.GITHUB_REF_SLUG }} 
          echo "IMAGE=$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
